### ISSUE TITLE
[Question] false-positive propability behaviour and benchmark

### ISSUE THREAD

**Issue by be-a-panther** [hashlookup/poppy#14] opened 2024-08-07 11:27 UTC
src: https://www.misp-project.org/2024/03/25/Poppy-a-new-bloom-filter-format-and-project.html
> Benchmarks
> Dataset size: varies between 10MB and 7GB
> Data type: sha1 strings (40 bytes wide)
> False positive probability: 0.001 (0.1%)

The 10MB datasets contains around 200,000 entries.

1. How many datasets did you test?
2. Have you tested any smaller datasets?
3. the FPP depends on what values? I would guess, that this is defined at the creation based on the selected capacity and the FPP. Is this FPP then the upper limit or the lower limit? Or more like a wish and it gets maybe fulfilled.
4. As previously guessed: Is there a way to estimate what the FPP will be depending on the actual used capacity ?

I used the bench option to test against a PSS created bloomfilter:
```
Preparing dataset
Benchmarking filter: multi/v2/filterC_0.01.pop
	version                                  : 2
	capacity (desired number of elements)    : 5
	n (estimated number of elements)         : 5
	fpp (false positive probability)         : 0.01
	Length of data                           : 0.0B
	Size of bloom filter                     : 4.0KB

Query performance:
	dataset size: 640.0B (0MB)
	test size: 5

	condition: 90% of queried values are in filter
	query duration: 97ns
	query speed: 51546391.8 queries/s -> 6292.3 MB/s
	fp rate =   0

[...]
	condition: 60% of queried values are in filter
	query duration: 99ns
	query speed: 50505050.5 queries/s -> 6165.2 MB/s
	fp rate = NaN
[...]
```
- the `fp rate = NaN` is a bug?
- the `fp rate = xxx` should be a float or an integer? 
- `condition: 90% of queried values are in filter` should contain the absolute number of queried values

**Comment by qjerome** [comment] 2024-08-08 13:09
Hi @be-a-panther,

So many questions in your issue ! I'll try to answer them all.

The 10MB datasets contains around 200,000 entries.

1. How many datasets did you test?
**The 10MB dataset has been tested over 50 times so it is as if we tested 50 datasets of 10MB** 
2. Have you tested any smaller datasets? 
**No**
3. the FPP depends on what values? I would guess, that this is defined at the creation based on the selected capacity and the FPP. Is this FPP then the upper limit or the lower limit? Or more like a wish and it gets maybe fulfilled.
**The false positive probability is something that is fixed by the creator of the filter. This is a theoretical value and your filter shouldn't have a real FPP that deviates too much from this value. This is why it is important to benchmark it.**
4. As previously guessed: Is there a way to estimate what the FPP will be depending on the actual used capacity ?
**The size (not capacity) of the filter is computed from the target FPP and the capacity (number of items we want to store). For a given capacity, the lower FPP the bigger the filter.**

- the `fp rate = NaN` is a bug?
**Maybe due to the very little number of elements in your filter**
- the `fp rate = xxx` should be a float or an integer? 
**Expected to be a float in [0; 1]. If only a few data is tested it can be 0 but if a significant amount of data is tested, it must be close to the FPP of the filter.**  
- `condition: 90% of queried values are in filter` should contain the absolute number of queried values
**Not sure I understand your question ! It means we are testing with a dataset made of 10% not in the filter, 90% in the filter. The percentage in/out should not impact `fp rate` it is just to measure query performance under different scenarios.**

**Comment by be-a-panther** [comment] 2024-08-09 09:23
thank you for the answers. Maybe the github discussion section would be better for this:

3. the FPP depends on what values? I would guess, that this is defined at the creation based on the selected capacity and the FPP. Is this FPP then the upper limit or the lower limit? Or more like a wish and it gets maybe fulfilled.
> The false positive probability is something that is fixed by the creator of the filter. This is a theoretical value and your filter shouldn't have a real FPP that deviates too much from this value. This is why it is important to benchmark it.

I did benchmark the bloomfilter:
![image](https://github.com/user-attachments/assets/b138c7bc-f49a-4434-9ea5-6cc73fdde937)
I can not explain those values other than that the bloomfilter does not work for small values. I run currently test with smaller datasets, different FPP and different capacities. All those values are IPv4 Addresses which a then saved as PSS(blake2b, 'infected'). 


- `condition: 90% of queried values are in filter` should contain the absolute number of queried values
> Not sure I understand your question ! It means we are testing with a dataset made of 10% not in the filter, 90% in the filter. 
The percentage in/out should not impact fp rate it is just to measure query performance under different scenarios. 

In my case the input was 5 entries, how many values where then tested? The 10% of values, which are not in the filter are in this case zero or one value?

My intention is to determine the lower boundaries, where the benchmark makes sense to use. Otherwise to warn or to exit, that this is not reliable.

**Comment by qjerome** [comment] 2024-08-09 09:44
I am sorry but I don't understand what you're testing. If you want me to be able to help you, please give me information I can use to replicate the exact same tests/benchmark on my side.

**Comment by be-a-panther** [comment] 2024-08-09 10:31
I'm testing the real false-positive behavior. I took 5 IPv4 Addresses and hashed each with blake2b. Those 5 lines were then put into a bloomfilter. I generated a set of bloomfilters with different pre-selected FPP AND two different capacities (c=5 or c=100000).
Afterwards I generated a full IPv4 set , which was hashed with blake2b too and the tested against each of those bloomfilters. After each test I counted how often poppy returned a true (like "is in the bloomfilter"). 
Those values are written down in column A (preselected FPP),B (capacity just fitting with c=5) and C (capacity much bigger). column D and E contains the estimated count in relation to the preselected FPP and the capacity.  (I'm aware that this value can only be vague and will always differs from the reality)

However:
- if the bloomfilter has only a capacity of 5 and 5 entries are put into it, the best you can get is 21 hits.
- if the bloomfilter has a bigger capacity of 100000 and 5 entries are put into it, the best you can get is 5 hits.
- It tends to jump at a FPP of 20% and at 50%
- the measured hits and the estimated hits are completely unrelated, not even in a scale.
- I would expect a little more linearity in the behavior

**Comment by qjerome** [comment] 2024-08-09 11:53
Your only concern should be fp rate, which you do not compute because count aggregates both FP + TP if I am not mistaking.
To see if the filter works as intended you should compute its real FP rate. 

On a 5 capacity with 5 entries it returns 21 hits on all IPv4 addresses: meaning that you have (21-5)=16 false positives, which is quite low on a full set (2^32) of IPv4 addresses. But again you need to compute the real FP rate not only positive counts that doesn't give any valuable information.

The way version 2 of poppy is implemented explains completely the non-linear behavior you observe.
Is this an issue that the behavior is not linear ?

**Comment by be-a-panther** [comment] 2024-08-10 09:49
It is correct, it is TP + FP.  But 16/5 is 3.2, which is more than a end user would except, especially if the capacity is the same amount as the input. In the case of 5 elements I would except by a FPP of 20% one FP.

Even better, because the input is 64bytes due the hashing with blake2b. The IPv4 would only have between 20 and 44bytes (char-> hex)

I have the requirement to get the end user perspective on the FP rate. 

Maybe the version 1is better fitting our requirements.

**Comment by qjerome** [comment] 2024-08-11 17:36
FP / TP (i.e. 16/5 in your case) isn't  the definition of FP rate.
FP rate is given by the formula: FP / (FP + TN) (see: https://en.wikipedia.org/wiki/False_positive_rate)

**Comment by be-a-panther** [comment] 2024-08-12 11:08
Yeah, and this is my problem (in understanding). What is the potential TN?
- My intentional brute-force range (in this case string representation of IPv4)
- The technical input range (64byte long blake2 hashes)
- the capacity of the bloom filter
- the amount of entries which were added to the bloomfilter
- the collision resistance of the wyhash?

**Comment by qjerome** [comment] 2024-08-12 11:34
TN is true negative, so all the things not supposed to be in your filter actually reported as not being in the filter.
Assuming you are testing the full IPv4 range (i.e. N=2^32) given the formula: N = FP + TN means TN = N - FP

**Comment by be-a-panther** [comment] 2024-08-14 12:58
This seems a little bit odd to me. Because I have the knowledge, that the bloomfilter contains only strings of IPv4.

> The false positive rate is FPR = FP / (FP + TN) 
> where FP  is the number of false positives, TN is the number of true negatives and N = FP + TN is the total number of ground truth negatives. 

I would assume, that I have to calculate the `total number of ground truth negatives`. Which should be somehow a static term, like the complete search space or the limited search space of the bloom filter.

**Comment by qjerome** [comment] 2024-08-14 13:17
Your TN is not complicated to compute ...
You know N (the number IPv4 you're testing against the filter) and FP (the number of IPs reported as being in the filter while they are actually not)

**Comment by be-a-panther** [comment] 2024-08-14 14:20
Well, if I only test the precalculated FP and use intentionally TN=0, then it i get a FPR=1. This is not useful.

**Comment by qjerome** [comment] 2024-08-16 07:57
TN is not something you are fixing ... This is something which is given by a run over a filter. If you have TN=0 it means FP==N and thus that your filter is empty and it returns that all IPs are inside, which I doubt !

**Closed as completed** 2024-08-29 04:25 UTC
